### ISSUE TITLE
Multiple event loops created cause failures

### ISSUE THREAD

**Issue by ljstephenson** [m-labs/thorlabs_tcube#3]
With the recent restructuring of sipyco to use `asyncio.new_event_loop()` within `simple_server_loop`, multiple event loops are created because `asynserial.AsyncSerial` creates its own event loop/gets an existing loop. This means that the driver does not work:

```
(artiq-dev) C:\Users\rabi>aqctl_thorlabs_tcube -vv --no-localhost-bind --bind 68810maglab4 -p 5000 -P tdc001 -d COM9
DEBUG:asyncio:Using proactor: IocpProactor
DEBUG:asyncio:Using proactor: IocpProactor
DEBUG:sipyco.pc_rpc:calling ping()
DEBUG:thorlabs_tcube.driver:sending: <Message MGMSG.HW_REQ_INFO p1=0x00 p2=0x00 dest=0x50 src=0x01>
WARNING<11>:thorlabs_tcube.driver:ping failed
Traceback (most recent call last):
  File "c:\users\rabi\scratch\thorlabs_tcube\thorlabs_tcube\driver.py", line 277, in ping
    await self.hardware_request_information()
  File "c:\users\rabi\scratch\thorlabs_tcube\thorlabs_tcube\driver.py", line 269, in hardware_request_information
    return await self.send_request(MGMSG.HW_REQ_INFO,
  File "c:\users\rabi\scratch\thorlabs_tcube\thorlabs_tcube\driver.py", line 212, in send_request
    await self.send(Message(msgreq_id, param1, param2, data=data))
  File "c:\users\rabi\scratch\thorlabs_tcube\thorlabs_tcube\driver.py", line 193, in send
    await self.port.write(message.pack())
RuntimeError: Task <Task pending name='Task-12' coro=<Server._handle_connection_cr() running at C:\Users\rabi\Anaconda3\envs\artiq-ndscan-dev\lib\site-packages\sipyco\pc_rpc.py:614> cb=[AsyncioServer._client_done()]> got Future <_OverlappedFuture pending overlapped=<pending, 0x207f0e094c0>> attached to a different loop

Caught Ctrl-C, terminating...
ERROR<6>:asyncio:Cancelling an overlapped future failed
future: <_OverlappedFuture pending overlapped=<pending, 0x207f0e094c0>>
Traceback (most recent call last):
  File "C:\Users\rabi\Anaconda3\envs\artiq-ndscan-dev\lib\asyncio\windows_events.py", line 71, in _cancel_overlapped
    self._ov.cancel()
OSError: [WinError 6] The handle is invalid
```

I can work around this by just using a copy of the code from `simple_server_loop` and omitting the creation of a new loop; would it perhaps make more sense for `simple_server_loop` to check for an existing loop before creating a new one?

**Comment by ljstephenson** [comment]
Ah,  I see now that changing `simple_server_loop` is non-trivial, since `asyncio.get_running_loop()` can only be called within a coroutine. Thoughts @sbourdeauducq ?

**Comment by sbourdeauducq** [comment]
fixed and tested on hardware
